airgradienthq/arduino

AirGradient.cpp

Solves https://github.com/airgradienthq/arduino/issues/9

Added return to compile with platformIO

---

AirGradient.cpp
examples/C02_PM_SHT_OLED_WIFI/C02_PM_SHT_OLED_WIFI.ino

The library and example do not work for me without these fixes.

correct math.h header and specify wificlient as per new http library requirement.

---

examples/ONE_I-9PSL/ONE_I-9PSL.ino

- Fix  server config `ledBarTestRequested` not worked

updated `ledBarTestRequested`

---

examples/ONE/ONE.ino

Fix OpenMetrics typo: celcius -> celsius

---

.github/workflows/check.yml
examples/ONE/ONE.ino
examples/OneOpenAir/OneOpenAir.ino
examples/Open_Air/Open_Air.ino
library.properties
src/AirGradient.cpp

- Add example OneOpenAir that can run for both ONE and OPEN_AIR board
- Bug fix

Bugfix and add example

---

examples/OneOpenAir/OtaHandler.h

Format code with tab size = 2 instead of 4

re-format source code

---

examples/OneOpenAir/OneOpenAir.ino

SSID `airgradient` and  password `cleanair` are set after keep pressing led test button until the end of the test on startup

Code for autoconnect to: airgradient:cleanair

---

docs/local-server.md

Reformat JSON in docs

---

docs/local-server.md

Fixes https://github.com/airgradienthq/arduino/issues/157

Update configuration parameters

---

examples/OneOpenAir/OneOpenAir.ino
src/AgValue.h

Add firmware update schedule each 60min.
Print message log:
WiFi Connected and perform OTA
```
firmwareCheckForUpdate:
firmwareCheckForUpdate: Perform
```
WiFi is not connected, ignore perform OTA
```
firmwareCheckForUpdate:
firmwareCheckForUpdate: Ignored
```

OTA update each 60 min

---

examples/OneOpenAir/OneOpenAir.ino
src/AgWiFiConnector.cpp
src/AgWiFiConnector.h

The display show `Rebooting...` but device not reboot.

[Fix] Reboot device after WiFi Configure porttal timeout

---

docs/local-server.md

Fix typos in docs

---

examples/OneOpenAir/OneOpenAir.ino

Currently display show `Add to Dashboard` message if sensor fetch configuration from sever failed. But  the message only show if return code is `400`

Fix display message is not correct.

---

examples/OneOpenAir/OneOpenAir.ino

On factory reset set the WiFi connection to `airgradient` AP

Set WiFi connect to default WiFi on factory reset

---

src/AirGradient.cpp

Update round 2 decimal digit value on JSON [support negative value](https://github.com/DaveGamble/cJSON/issues/175#issuecomment-2253721996)

`round2` support negative value

---

src/AgApiClient.cpp

API client log post data

---

src/AgValue.cpp
src/AgValue.h
src/PMS/PMS.cpp
src/PMS/PMS.h
src/PMS/PMS5003.cpp
src/PMS/PMS5003.h
src/PMS/PMS5003T.cpp
src/PMS/PMS5003T.h

Add JSON `PMS5003T_FwVer` on data send to cloud
- Single channel:
```json
{
"PMS5003T_FwVer": 2
}
```
- Two channel:
```json
{
"channels":{
"1":{
"PMS5003T_FwVer": 2
},
"2":{
"PMS5003T_FwVer": 2
}
}
}
```

Send PMS5003T firmware version to Ag Cloud

---

examples/OneOpenAir/OneOpenAir.ino
src/AgStateMachine.cpp
src/AirGradient.cpp
src/AirGradient.h

OpenAir handle `ledBarTestRequested` by blink the LED period 50ms for 10 seconds.

`OpenAir` handle `ledBarTestRequested`

---

examples/OneOpenAir/OneOpenAir.ino
src/AgOledDisplay.cpp
src/AgWiFiConnector.cpp
src/PMS/PMS.cpp
src/PMS/PMS.h
src/PMS/PMS5003.cpp

Cubic has PM sensors that are compatible with the Plantower PMS5003 series, see https://en.gassensor.com.cn/IndoorPMSensor/list.html.
With this PR we are able to support the PM2009X model.

Changed PM initialization to also support the Cubic PM2009X

---

src/AgValue.cpp

- Resolve the PM compensate input temperature instead of humidity
- Fix #234

Fix pm compensation: receiving temperature instead of humidity

---

examples/BASIC/BASIC.ino
examples/DiyProIndoorV3_3/DiyProIndoorV3_3.ino
examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino
examples/OneOpenAir/OneOpenAir.ino

- Hardware watchdog feed i independent from POST to Airgradient server

Update hardware watchdog reset

---

src/AgConfigure.cpp

Fixes what looks like a copy/paste error.

Fix default for ledBarMode

---

examples/BASIC/BASIC.ino
examples/DiyProIndoorV3_3/DiyProIndoorV3_3.ino
examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino
examples/OneOpenAir/OneOpenAir.ino

Addressing this issue https://github.com/airgradienthq/arduino/issues/253

Always increment bootcount when send measurements data is scheduled

---

docs/local-server.md
examples/OneOpenAir/OneOpenAir.ino
src/AgStateMachine.cpp
src/AgStateMachine.h

- Fix flicker by not always clearing whole led bar when update, but per led index
- Fix typo and comment

Fix flicker on led bar led state change

---

src/AgValue.cpp

**Changes**
Previously measurementType check if undefined is the same value as invalid temperature value. Fix by adding new state variable.

Fix invalidate value check for getAverage function

---

examples/OneOpenAir/OneOpenAir.ino
src/AgConfigure.cpp
src/AgValue.cpp

- Fix TVOC and NOx payload position when post measures for cellular network option
- Fix mqtt host still exist on local when on server is already disabled
- Change log level when temperature and humidity correction not found from warning to info
- MQTT through cellular network options not available yet, ignore mqtt host configuration

Fix bugs from 3.3.1 release
