airgradienthq/arduino

examples/ONE_V9/ONE_V9.ino
We never use this variable, so there's no reason to declare or define it.
=> Delete unused displayTop global

src/Display/Display.h, src/S8/S8.h, src/Sgp41/Sgp41.h, src/Sht/Sht.h
This fixes build breakage on case-sensitive filesystems (e.g. Linux) with errors like:
```
src/Display/Display.h:4:10: fatal error: ../main/BoardDef.h: No such file or directory
```
=> Fix path capitalization

.github/workflows/check.yml
This commit adds a GitHub Actions workflow that, on every push/pull request, will check that every single example successfully compiles on every board it supports. That is, it it will check compilation on:
- ESP8266 for BASIC_v4, TestCO2, TestPM and TestSht
- ESP32 for ONE_I-9PSL, Open_Air, TestCO2, TestPM and TestSht
This provides the first building block towards a Continuous Integration (CI) pipeline and prevents build breakages from making it to master.
Ideally this should also run tests on the examples (i.e. verifying that the example boots successfully and sends metrics), but for now this will at least ensure the build is not obviously broken.
Note that, at the time of this PR, the worfklow is [broken](https://github.com/dechamps/airgradient/actions/runs/8037836959) because of #56 …
=> Add compile check GitHub Actions workflow

examples/ONE_I-9PSL/ONE_I-9PSL.ino
This commit adds a new feature to the One V9 (ONE_I-9PSL) firmware: support for exposing metrics to Prometheus (or any other ingestor compatible with the OpenMetrics format).
With this change, the AirGradient device will make metrics available on the standard HTTP `/metrics` endpoint, out-of-the-box, with no need to do anything else. All the user has to do is add their device address as a target to their scrape config on their Prometheus server.
For more information on Prometheus and OpenMetrics, see:
- https://prometheus.io/docs/instrumenting/exposition_formats/
- https://openmetrics.io/
- https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
This obsoletes projects such as:
- https://github.com/geerlingguy/airgradient-prometheus/tree/ebfa8d0ac6d8c47649e4 …
=> Add support for Prometheus/OpenMetrics to One V9

.github/workflows/check.yml
This fixes the following check GitHub Actions workflow failure that would otherwise occur on pull requests (but not on pushes/branches):
```
Error installing Git Library: Library install failed: object not found
```
=> Fix check workflow failing on pull requests

examples/ONE/ONE.ino
- Underscore before names per https://github.com/espressif/arduino-esp32/issues/962
- Only one service per port
The combination of both changes is needed to make the service discoverable in OpenHAB
The removal of the published http service is maybe something you don't want, but as long as it doesn't serve web pages it is maybe OK?
=> Fix MDNS Service Discovery:

examples/ONE/ONE.ino
Please see: https://prometheus.io/docs/practices/naming/#base-units
Also, thanks a lot for this support, I had my own exporter that I can now delete :)
=> [ONE/Prometheus] Use full unit in temperature metric

examples/ONE/ONE.ino
This makes it easier for integrations which talks both to the cloud and to the Cloud API to support the same format for reading current measures.
In practice this adds the firmware version and led mode to the output, and changes the writing of pm003Count, tvocIndex and noxIndex to use the same spelling as for the documented cloud API.
=> Standardize result of /measures/current

examples/OneOpenAir/OtaHandler.h
As per title, with this PR we better handle these cases
1. The server returns a 304, this means that the firmware on the device is already up to date. There is no need for additional steps.
2. The server returns a e.g. 400, this normally means that the client is on some unofficial firmware. We don't download in such case
=> OTA Update, better handle the 304 and 400 case

examples/OneOpenAir/OpenMetrics.cpp
I noticed that PM 0.1, 2.5, and 1.0 data on my AirGradient ONE was being reported by `/measures/current` but not `/metrcis`. This MR brings those two endpoints better into parity.
I also noticed a comma went missing causing Prometheus to no longer be able to parse the metrics. Fixed that, too.
As a side note, I notice that the logic for handling a measurement seems to be duplicated between `AgValue.cpp` and `OpenMetrics.cpp`. I suspect we'll keep seeing this kind of disparity between these endpoints until that logic is unified.
=> Report PM data to metrics API for AirGradient ONE

examples/OneOpenAir/OneOpenAir.ino, src/AgOledDisplay.cpp, src/AgOledDisplay.h
The LED bar will turn off from power up after init if brightness is 0%. 
The display also keep the brightness 1% for setup and completely turn off after WiFi Connector done.
=> Turn off LED bar and Display if brightness is 0%, fix #114

docs/local-server.md
=> Reformat table

examples/OneOpenAir/OneOpenAir.ino
On offline mode the device will not perform the WiFi connection mean the WiFi STA is not enabled. On factory reset it's always failed if call `WiFi.disconnect(true, true)` to reset WiFi connection cause WiFi is not enabled.
=> [Fix] WiFi not reset on offline mode

examples/BASIC/BASIC.ino, examples/OneOpenAir/OneOpenAir.ino
1. Rename macro name
3. Currently the server GET configure is `15` sec for `OneOpenAir.ino` and `30` sec for `BASIC.ino` . Now set to `60` sec
=> [Fix] Too many server GET config request

examples/OneOpenAir/OneOpenAir.ino
- Show message on display after LED bar button test button still pressed to reset WiFi connection to `airgradient` WiFi.
- Clear display after show rebooting message.
=> Update the message show on display

examples/OneOpenAir/OneOpenAir.ino
OpenAir set WiFi connect to default `airgradient` on factory reset
=> OpenAir set WiFi connect to `airgradient` on factory reset

src/AgConfigure.cpp
Currently if `configurationControl` set to `cloud` always return failed  #174 
This update will handle 'configurationControl' should return success if set `cloud`.
=> [Fix] Local `configurationControl` return failed if set `cloud`

src/AgStateMachine.cpp
LED bar show `orange`  and `purple` incorrect. #161
=> Correct LED bar show sensor value level color

src/AgOledDisplay.cpp
The `NOx` label show wrong position to area of PM4.5. Now move it to the area of VOC and NOx
Before
After
=> `NOx` show incorrect position on display

src/Main/utils.cpp, src/PMS/PMS.cpp, src/PMS/PMS.h
- Add invalid value for PMS03Count
- Optimize code operator
- Fix: PMS5003T temperature has only return positive value. In case the temperature < 0 read return value is always invalid.
=> sensor value out of range

src/AgOledDisplay.cpp, src/AgValue.cpp, src/PMS/PMS.cpp, src/PMS/PMS.h, src/PMS/PMS5003.cpp, src/PMS/PMS5003.h, src/PMS/PMS5003T.cpp, src/PMS/PMS5003T.h
Update the PM2.5 calculate formula #182 . The correct value show on device display or use on local only.
=> correct pm2.5 formula to show value on display

src/AgApiClient.cpp
Log URL and response code message for HTTP request to AG server
=> Add log message HTTP request and response to AG server

src/PMS/PMS.cpp
- Fix: formular missing pow of 2
- Optimize for float number calculations
- Fix #225
=> Fix pm2.5 compensation formula

examples/BASIC/OpenMetrics.cpp, examples/DiyProIndoorV3_3/OpenMetrics.cpp, examples/DiyProIndoorV4_2/OpenMetrics.cpp, examples/OneOpenAir/OpenMetrics.cpp, src/AgOledDisplay.cpp, src/AgValue.cpp, src/Main/utils.cpp, src/Main/utils.h, src/PMS/PMS.cpp, src/PMS/PMS.h, src/PMS/PMS5003.cpp, src/PMS/PMS5003.h, src/PMS/PMS5003T.cpp, src/PMS/PMS5003T.h
Update missing add PM2.5 compensated before show on display. #221
=> [Fix] PM2.5 compensated show on display

examples/OneOpenAir/OneOpenAir.ino, examples/OneOpenAir/OpenMetrics.cpp, platformio.ini, src/AgValue.cpp, src/PMS/PMS5003TBase.cpp, src/PMS/PMS5003TBase.h
Correct print log message number format, #218
=> Fix print log message number format

examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino, examples/OneOpenAir/OneOpenAir.ino, src/AgWiFiConnector.cpp, src/AgWiFiConnector.h
WiFi auto connect to default `airgradient` if last connection saved is empty. The WiFi connection empty after factory reset or without connect to any WiFi before
=> Add default WiFi connect

examples/BASIC/BASIC.ino, examples/DiyProIndoorV3_3/DiyProIndoorV3_3.ino, examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino, examples/OneOpenAir/OneOpenAir.ino
PM sensor log firmware version along side with PM value: `PM firmware version: 151`
```10:35:43.206 > PM1 ug/m3: 11
10:35:43.207 > PM2.5 ug/m3: 23
10:35:43.207 > PM10 ug/m3: 27
10:35:43.207 > PM0.3 Count: 2169
10:35:43.207 > PM firmware version: 151
10:35:43.494 > Temperature in C: 26.79
10:35:43.494 > Relative Humidity: 82
10:35:43.494 > Temperature compensated in C: 26.79
10:35:43.494 > Relative Humidity compensated: 82
```
=> Add log: PMS5003x sensor print log firmware version

src/AgStateMachine.cpp
- PM value show status on LED bar use compensate value
=> Fix: Correct LED bar show PM status

examples/OneOpenAir/OneOpenAir.ino, src/AgStateMachine.cpp
1. Fix showing `server N/A` when `postDataToAirGradient` is set to `False`. This case occur when `postDataToAirGradient` set to `false` locally while previously device is failed to post data to server. The status stayed on the display.
2. Merge update network related status error for led bar and oled display in 1 function.
=> Fix showing "Server N/A" when postDataToAirGradient is false

src/AgOledDisplay.cpp
Heya!
Currently, the only affect the brightness setting has with the DIY boards is an attempt to set the contrast. 
Setting the contrast to 0 does not have any effect.  This appears to be a known limitation for these display boards.
Instead clearing the display buffer and calling show to display a blank screen.
Personal quality of life feature that I've been using that I figured I would attempt to add. 
Assuming this repo welcome contributions, if not let me know!
Thanks in advance!
=> Added support clearing display at 0 brightness for DIY Boards

examples/BASIC/BASIC.ino, examples/BASIC/LocalServer.cpp, examples/BASIC/OpenMetrics.cpp, examples/DiyProIndoorV3_3/DiyProIndoorV3_3.ino, examples/DiyProIndoorV3_3/LocalServer.cpp, examples/DiyProIndoorV3_3/OpenMetrics.cpp, examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino, examples/DiyProIndoorV4_2/LocalServer.cpp, examples/DiyProIndoorV4_2/OpenMetrics.cpp, examples/OneOpenAir/LocalServer.cpp, examples/OneOpenAir/OneOpenAir.ino, examples/OneOpenAir/OpenMetrics.cpp, src/AgOledDisplay.cpp, src/AgStateMachine.cpp, src/AgValue.cpp, src/AgValue.h, src/PMS/PMS.cpp, src/PMS/PMS.h, src/PMS/PMS5003.cpp, src/PMS/PMS5003.h, src/PMS/PMS5003T.cpp, src/PMS/PMS5003T.h
Main changes is restructuring Measurement class on AgValue files. Each measurements has average value that are always calculated based on max period length (`calculateMaxPeriod()`) set for moving average calculation.
1. Every measurements data from each sensor have an average value which are sent to AirGradient server, MQTT and Local Server fetch. On oled display and led bar indication still using last reading value.
2. Relative humidity now is in float 2 decimals precision (except showing on oled display)
3. Remove ESP restart when PM sensor read failed on _X_ times
4. Interval for SHT sensor reading now set to 6s
5. Optional debug every reading interval to serial monitor. Sensor debug to serial monitor is the moving average value
6. `PMSBase::compensate` using `float`  data type for …
=> Restructure Measurements class

docs/local-server.md, examples/OneOpenAir/OneOpenAir.ino, src/AgValue.cpp, src/AgValue.h, src/PMS/PMS.cpp, src/PMS/PMS5003.cpp, src/PMS/PMS5003.h, src/PMS/PMS5003T.cpp, src/PMS/PMS5003T.h
- Standard particle of each PM concentration
- Particle count `1.0`, `2.5` and `10`. Except `10` only for indoors monitor.
- `pm01Standard` 
- `pm02Standard`
- `pm10Standard`
- `pm01Count`
- `pm25Count`
- `pm10Count`
See `docs/local-server.md` for more detail of each field above
=> Send all particle counts and standard particle values provided by the PMS sensor

docs/local-server.md, examples/OneOpenAir/OneOpenAir.ino, src/AgConfigure.cpp, src/AgOledDisplay.cpp, src/AgStateMachine.cpp, src/AgValue.cpp, src/AgValue.h
- Measurements on display and led bar indicator using average value instead of last reading value
- Fix `pm02Compensated` value when corrections config is `none`
- Decrease moving average period length by 80%, change from 50%
- Add more command examples to set corrections locally on `local-server.md`
=> Values on display and led bar using measurement average values

docs/local-server.md, src/AgConfigure.cpp, src/AgStateMachine.cpp, src/AgValue.cpp
1. Fix pm2.5 compensated value with EPA enabled on top of SLR correction
2. CO2 led bar indicator follow AG dashboard
3. Add other check to handle parsing invalid json string with number at the front of the json object. Eg. `1ca \n{"data": 123}`
=> Fix EPA compensated on top of SLR correction

src/AgOledDisplay.cpp, src/AgValue.cpp
=> (Basic DIY): Fix temperature parsing in OLED and debug for Basic DIY version

examples/OneOpenAir/OneOpenAir.ino, src/AgValue.cpp
On version 3.1.13 and 3.1.21, when monitor finish setup() function, display show 0 values for all measurements for a moment.
Make sure scheduler for sensor readings run first before display to oled and post to server. By reset display and post data scheduler at the end of setup function.
https://github.com/user-attachments/assets/867325e9-e865-4960-a468-d6d850ab05eb
=> Fix display 0 measurements value on boot

src/AgApiClient.cpp, src/AgApiClient.h
Sometimes when device have bad internet connection, http client failed to connect to airgradient server. That makes these errors occur
```
[2417017][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -1
[ApiClient] Info: GET: https://hw.airgradient.com/sensors/airgradient:aaaaaaaaaa/one/config
[ApiClient] Info: Return code: -1
```
```
[887570][E][WiFiGeneric.cpp:1583] hostByName(): DNS Failed for hw.airgradient.com
[ApiClient] Info: GET: https://hw.airgradient.com/sensors/airgradient:aaaaaaaaaaa/one/config
[ApiClient] Info: Return code: -1
```
Return code indicate connection refused, but it is misleading. After set log level to verbose, it shows the problem:
```
13:20:22.092 > [321705][V][HTTPClient.cpp:252] beginInternal(): url: …
```
=> HTTP client failed/timeout to establish connection to airgradient server

docs/local-server.md, examples/BASIC/BASIC.ino, examples/BASIC/OpenMetrics.cpp, examples/DiyProIndoorV3_3/DiyProIndoorV3_3.ino, examples/DiyProIndoorV3_3/OpenMetrics.cpp, examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino, examples/DiyProIndoorV4_2/OpenMetrics.cpp, examples/OneOpenAir/OneOpenAir.ino, examples/OneOpenAir/OpenMetrics.cpp, src/AgApiClient.cpp, src/AgApiClient.h, src/AgConfigure.cpp, src/AgConfigure.h, src/AgWiFiConnector.cpp
1. `disableCloudConnection` config added to disable every cloud connection to airgradient server
2. `disableCloudConnection` not applied for DIY model
3. `local-server.md` updated, describing `offlineMode` and `disableCloudConnection`
4. Adding more verbose logs regarding ignored connection to airgradient server
```
> Ignore fetch server configuration. Either mode is offline or cloud connection disabled or configurationControl set to local
> Ignore send data to server. Either mode is offline or cloud connection is disabled or post data to server disabled
> firmwareCheckForUpdate: mode is offline or cloud connection disabled, ignored
```
=> Fully disable cloud connection to airgradient server option

docs/local-server.md, examples/BASIC/BASIC.ino, examples/BASIC/LocalServer.cpp, examples/BASIC/OpenMetrics.cpp, examples/DiyProIndoorV3_3/DiyProIndoorV3_3.ino, examples/DiyProIndoorV3_3/LocalServer.cpp, examples/DiyProIndoorV3_3/OpenMetrics.cpp, examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino, examples/DiyProIndoorV4_2/LocalServer.cpp, examples/DiyProIndoorV4_2/OpenMetrics.cpp, examples/OneOpenAir/LocalServer.cpp, examples/OneOpenAir/OneOpenAir.ino, examples/OneOpenAir/OpenMetrics.cpp, src/AgConfigure.cpp, src/AgConfigure.h, src/AgOledDisplay.cpp, src/AgStateMachine.cpp, src/AgValue.cpp, src/AgValue.h, src/App/AppDef.h
1. Apply temperature and humidity correction for indoor and outdoor monitor
2. Correction configuration can be set from cloud or local server
3. Correction applied to display, led bar, local server and open metrics
4. Add docs on how to apply correction locally
5. Add AirGradient and Configuration object to Measurements class
=> Apply temperature and humidity correction based on configuration

.github/workflows/check.yml
Instead of straight CLI, uses the arduino/compile-sketches action.
One immediate benefit is enabling deltas reports
https://github.com/arduino/compile-sketches/tree/v1.1.2/?tab=readme-ov-file#enable-deltas-report
This can show the change in flash and ram compared to the previous run https://github.com/MallocArray/arduino/actions/runs/12954136400/job/36135424360
```
Compiling sketch: examples/OneOpenAir
Compilation time elapsed: 6s
Change in flash: 147290 (7.49%)
Change in RAM for global variables: 2280 (0.7%)
```
A future improvement could be to also add https://github.com/arduino/report-size-deltas that can generate a comment on a PR that also shows the delta information.
=> Update workflow to use compile-sketches action

.github/workflows/check.yml, .gitignore, examples/OneOpenAir/OneOpenAir.ino
- Enable cellular AT command debug when in network registration. To better understand if cellular module not able to connect to the network
- On boot, airgradient-client change cellular init timeout to 5 mins
=> Enable cellular AT command debug when in network registration

examples/OneOpenAir/OneOpenAir.ino
- When cellular client is not ready, the reason not only because of network not registered or module not responding, but can be something else (eg. HTTP AT command always return error). To make sure, will do cellular module power recycle and re-start network registration. _Changes on airgradient-client_
- Fix esp_log not come out on O-PP model
=> Restarting cellular module when cellular client is not ready

examples/OneOpenAir/OneOpenAir.ino
Cellular network options using wifi measurement interval as the constant reference to calculate max period
=> Calculate measurement average max period use the same constant

platformio.ini
So turns out `CORE_DEBUG_LEVEL` build flag is using `Serial0` which is connected to PM sensor that makes PM sensor send error measures values, even though USB_CDC is enabled,.
`CORE_DEBUG_LEVEL` build flag is used by airgradient libraries (airgradient-client and airgradient-ota) to print out esp_log. Now the libs using custom log macros to handle two environments which are Arduino and ESP-IDF so `CORE_DEBUG_LEVEL` can be removed.
The libs expecting `AG_LOG_LEVEL` defined so _agLogger.h_ able to compile the target log level needed.
_Notes: This PR temporarily link airgradient libs submodule to WIP branch. Will be changed after PR on those libs are merged._
=> Remove CORE_DEBUG_LEVEL that affected PM sensor reading

examples/OneOpenAir/OneOpenAir.ino, src/AgValue.cpp
- Include cellular signal in RSSI (dbm) when post measures
- But if signal value invalid, then don't include it. Follow the convention of other measures type.
=> Include cellular signal in RSSI (dbm) when post measures

examples/OneOpenAir/OneOpenAir.ino
1. Power cycle cellular module control directly on main, if airgradient client not ready for more than 1 hour
2. If in 2 hour airgradient client still not ready, then esp restart. Has redundant check in both main and networking tasks.
3. Transmit measures only if measurement cycle queue size is divisible by 3
=> Improve cellular client reconnection

examples/OneOpenAir/OneOpenAir.ino, src/Sgp41/Sgp41.cpp, src/Sgp41/Sgp41.h
- Add a pause and resume SGP41 reading to its task, so no need to reset SGP41 algorithm object
- Use latest airgradient-ota library, by improving ota sequence to have a more accurate event. Please see: #https://github.com/airgradienthq/airgradient-ota/pull/2 . Because of this, no need to pause SGP41 task every time doing OTA check. Only pause when actually know that firmware update is available.
=> Fix incorrect TVOC / NOx values when when network option is cellular 

examples/OneOpenAir/OneOpenAir.ino, examples/OneOpenAir/OpenMetrics.cpp, examples/OneOpenAir/OpenMetrics.h
Previously, `airgradientClient` was passed to `openmetrics` before it was initialized. This has been fixed by separating the passing of `airgradient` and `airgradientClient` to `openmetrics`, allowing `airgradientClient` to be passed only after it has been initialized.
=> Fix calling airgradient client before initialization on open metrics

.gitmodules
This should fix #307 by using a relative path for the submodule URLs. Users that clone the repo with HTTPS will also clone the submodules with HTTPS, and users that clone the repo with SSH will clone the submodules with SSH.
We keep the username in the path so that forks don't need to also fork the submodules.
For example, the configuration below would not work for a user that forks only the main repo and not the submodules because git would look for the submodules in the namespace of the forking user.
```
[submodule "src/Libraries/airgradient-client"]
path = src/Libraries/airgradient-client
url = ../airgradient-client.git
[submodule "src/Libraries/airgradient-ota"]
path = src/Libraries/airgradient-ota
url = ../airgradient-ota.git
```
---
This can be tested by cloning the branch on a …
=> Fix failing to clone submodules recursively

examples/OneOpenAir/OneOpenAir.ino
Bootloop happen when cloud connection disabled because of calling return inside a task function making it crash. 
Issue: #312 
- Change `return` to `continue` to ignore the rest of transmission code. 
- Ignore OTA check on boot
=> Fix bootloop when cloud connection is disabled

examples/OneOpenAir/OneOpenAir.ino, src/AgValue.cpp, src/AgValue.h
Improve logging by log measurement values on a same schedule and more readable format
Example:
```
14:15:02.438 > CO2 = 153.00 ppm
14:15:02.438 > Temperature = 32.80 C
14:15:02.438 > Relative Humidity = 72.36
14:15:02.438 > TVOC Index = 0.0
14:15:02.438 > TVOC Raw = 33738.2
14:15:02.438 > NOx Index = 0.0
14:15:02.438 > NOx Raw = 16564.3
14:15:02.439 > [1] Atmospheric PM 1.0 = 0.67 ug/m3
14:15:02.439 > [1] Atmospheric PM 2.5 = 3.33 ug/m3
14:15:02.439 > [1] Atmospheric PM 10 = 4.17 ug/m3
14:15:02.439 > [1] Standard Particle PM 1.0 = 0.67 ug/m3
14:15:02.439 > [1] Standard Particle PM 2.5 = 3.33 ug/m3
14:15:02.439 > [1] Standard Particle PM 10 = 4.17 ug/m3
14:15:02.439 > [1] Particle Count 0.3 = 285.0
14:15:02.439 > [1] Particle Count 0.5 = 256.8
14:15:02.439 > [1] Particle Count 1.0 = 1.0 …
```
=> Improve measurements logging

examples/OneOpenAir/OneOpenAir.ino
_Only applied when network option is cellular_
Previously, after processing the vector `measurementCycleQueue`, we attempted to reduce memory usage by calling .resize() function. The `resize()` function changes the size of the vector (i.e., the number of elements), not its capacity. If called on an empty vector, it unintentionally fills the vector with default-initialized elements.
Replace resize by:
- Swaps the `measurementCycleQueue` with a fresh one having the desired reserved capacity only if the capacity exceeds the expected capacity.
- Otherwise, simply clears the vector.
=> Fix resizing measurement queue after post by cellular post

examples/OneOpenAir/OneOpenAir.ino, src/AgConfigure.cpp, src/AgConfigure.h
#322 
Change the way OneOpenAir examples update local configuration more realtime by using callback from Configuration class if there's an update.
=> Update configuration changes by callback

README.md
Fixes #335
There's useful documentation in the docs/ directory, but it's hard for users to discover it, as there are no links to it.
This change updates the README to add links to the inner docs pages for users interested in customizing and re-flashing firmware onto their devices as well as understanding the OTA update system.
=> Link to inner docs pages from main README

docs/local-server.md
The JSON example has an extra closing brace, causing the JSON to be invalid. The fix is to remove the stray closing brace.
=> Fix JSON example in /config docs

src/MqttClient.cpp
The `connected` flag was not updated when using auth. The MQTT payloads were not sent in such case.
=> fix: ensure connected flag set for both authenticated connections.

.github/workflows/check.yml, README.md, docs/howto-compile.md, docs/local-server.md, docs/ota-updates.md, examples/DiyProIndoorV4_2/DiyProIndoorV4_2.ino, examples/OneOpenAir/OneOpenAir.ino, examples/OneOpenAir/OpenMetrics.cpp, platformio.ini, src/AgApiClient.cpp, src/AgConfigure.cpp, src/AgValue.cpp, src/AgValue.h, src/AgWiFiConnector.cpp, src/AirGradient.cpp, src/AirGradient.h, src/Main/BoardDef.h, src/Main/StatusLed.h, src/PMS/PMS.cpp, src/PMS/PMS.h, src/PMS/PMS5003.cpp, src/PMS/PMS5003T.cpp, src/PMS/PMS5003TBase.cpp, src/PMS/PMS5003TBase.h, src/Sgp41/Sgp41.cpp
Trailing whitespace serves no purpose in code and only creates noise in PRs/commits when developers have their editors configured to delete trailing whitespace and they edit existing code.
This change eliminates all trailing whitespace from the repo and adds a Github Actions check to ensure that source files do not have trailing whitespace on merge.
This excludes the `scr/Libraries` directory, as those are vendored libraries that AirGradient doesn't own.
Related: https://github.com/airgradienthq/airgradient-client/pull/6
=> Eliminate trailing whitespace
